# Generated by Django 3.0.2 on 2020-01-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='send_massages',
            new_name='send_messages',
        ),
    ]
